apiVersion: v1
kind: ServiceAccount
metadata:
  name: extended-default-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extended-default-scheduler-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: extended-default-scheduler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-default-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: extended-default-scheduler
    algorithmSource:
      policy:
        configMap:
          namespace: kube-system
          name: extended-default-scheduler-policy
    leaderElection:
      leaderElect: true
      lockObjectName: extended-default-scheduler
      lockObjectNamespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-default-scheduler-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [
      {"name" : "PodFitsHostPorts"},
      {"name" : "PodFitsResources"},
      {"name" : "NoDiskConflict"},
      {"name" : "MatchNodeSelector"},
      {"name" : "HostName"}
    ],
    "priorities" : [
      {"name" : "LeastRequestedPriority", "weight" : 1},
      {"name" : "BalancedResourceAllocation", "weight" : 1},
      {"name" : "ServiceSpreadingPriority", "weight" : 1},
      {"name" : "EqualPriority", "weight" : 1}
    ],
    "extenders" : [{
      "urlPrefix": "http://localhost/thermal_scheduler",
      "filterVerb": "filter/thermal_filter",
      "prioritizeVerb": "prioritize/thermal_prioritize",
      "weight": 3,
      "enableHttps": false,
      "nodeCacheCapable": false
    }],
    "hardPodAffinitySymmetricWeight" : 10
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extended-default-scheduler
  namespace: kube-system
  labels:
    app: extended-default-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extended-default-scheduler
  template:
    metadata:
      labels:
        app: extended-default-scheduler
    spec:
      serviceAccountName: extended-default-scheduler
      volumes:
      - name: extended-default-scheduler-config
        configMap:
          name: extended-default-scheduler-config
      containers:
      - name: extended-default-scheduler-ctr
        image: gcr.io/google_containers/hyperkube:v1.16.3
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --config=/extended-default-scheduler/config.yaml
        - -v=4
        volumeMounts:
        - name: extended-default-scheduler-config
          mountPath: /extended-default-scheduler
      - name: thermal-extender-ctr 
        image: 10.0.0.100:5000/webberlh/thermal-extender:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          tcpSocket:
            port: 80
        ports:
          - containerPort: 80

